### ISSUE TITLE
申请使用https://pixiv.cat/代理

### ISSUE THREAD

**Issue by CeuiLiSA** [pixiv-cat/pixivcat-cloudflare-workers#2]
你好，我是pixiv第三方app shaft的开发人员。

https://pixiv.cat/
这个网站是用来查看pixiv插画作品原图的神器，很赞
shaft app内展示原图的时候用官方原版的方式加载图片，速度慢不说还容易挂掉。
所以请求允许我在app内内置pixiv.cat代理来查看作品原图，以提升用户体验，如果可以的话感激不尽

**Comment by jongcs** [comment]
已於Email回覆
