### ISSUE TITLE
Dose demo page support multi-image

### ISSUE THREAD

**Issue by hizo58** [pixiv-cat/pixivcat-cloudflare-workers#3]
Thanks for your great work on pixiv.cat, it always helps me a lot.

take pixiv id 79284472 as instance,
pixiv.cat/79284472.jpg tells that it has 2 pages within, and u need to select particular page number for presenting.
pixiv.cat/79284472-1.jpg presents as expected.

however,
https://demo.pixivcat.workers.dev/79284472.jpg doesn't get out as well as https://demo.pixivcat.workers.dev/79284472-1.jpg
said source is deleted.
do u have any idea on this? or just demo.pixivcat is an uncompleted demo that won't be released later then?

**Comment by jongcs** [comment]
This script do support multiple page illustration.
But I didn't turn the R-18 option on for the account that I used in this demo, that's why it returns deleted.
You can try other non-R-18 illustration in this demo, or deploy this script to your own Cloudflare Workers.
