### ISSUE TITLE
希望能提供除oauth.secure.pixiv.net以外的反向代理的API接口

### ISSUE THREAD

**Issue by Coder-Sakura** [pixiv-cat/pixivcat-cloudflare-workers#5]
你好！作者大大
我遇到的问题与[issue 4](https://github.com/pixiv-cat/pixivcat-cloudflare-workers/issues/4)是一样的，作者大大能不能提供一下除`oauth.secure.pixiv.net` 以外的其他反向代理API接口呢？
万分感谢！

**Comment by jongcs** [comment]
公開API代理接口容易遭到濫用，同一IP抓取量大容易受到rate limit，故沒有提供。

**Comment by Coder-Sakura** [comment]
好的，感谢作者大大的回复
