### ISSUE TITLE
可否使 pid 下单张图片和多张图片的代理链接格式一致

### ISSUE THREAD

**Issue by Jerry-FaGe** [pixiv-cat/pixivcat-cloudflare-workers#6]
大大您好，首先非常感谢您开发这个代理服务方便大家。

我想请问一下 [https://pixiv.cat/](https://pixiv.cat/) 这个代理可以支持下单张图片的 pid 也可以通过 `https://pixiv.cat/{pid}-0.jpg` 或者 `https://pixiv.cat/{pid}-1.jpg` 来返回图片么。

以为一般人通过某个随机 API 获取到某个P站原始链接后并不知道这个 pid 下有几张图片，而P站的原始链接无论是一张还是多张，第一张的 pid 后面都会有 _p0 这个后缀，例如：

- 单张  https://i.pximg.nat/img-original/img/2017/08/16/03/01/07/64440343_p0.png

- 多张  https://i.pximg.nat/img-original/img/2016/10/03/21/02/21/59291846_p0.jpg

这时如果开发人员想要用原始链接在后端重新拼接 https://pixiv.cat/ URL就比较不方便，先要尝试拼接出来的链接是否 404 才能确定正确的代理链接，麻烦大佬评估一下能否向上文说的那样增加支持。

**Comment by jongcs** [comment]
pixiv.cat 主要作為產生永久圖片連結使用 頻繁調用隨機且不常被存取的圖片會對伺服器造成負擔
若開發人員已經使用API取得pid資訊 則應該使用 [i.pixiv.cat](https://pixiv.cat/reverseproxy.html) 來取得圖片

**Comment by Jerry-FaGe** [comment]
了解了，我是偶然间发现在我的服务器上 https://i.pixiv.cat 与 https://pixiv.cat/ 的速度差别较大才尝试使用 https://pixiv.cat/ 来进行代理的，接下来我会尽量使用 https://i.pixiv.cat
