### ISSUE TITLE
How to allow CORS?

### ISSUE THREAD

**Issue by Ruriko** [pixiv-cat/pixivcat-cloudflare-workers#7]
I'm using this reverse proxy code that I found on your site

```
addEventListener("fetch", event => {
  let url = new URL(event.request.url);
  url.hostname = "i.pximg.net";

  let request = new Request(url, event.request);
  event.respondWith(
    fetch(request, {
      headers: {
        'Referer': 'https://www.pixiv.net/',
        'User-Agent': 'Cloudflare Workers'
      }
    })
  );
});
```
but I can't use it if I embed it to my main domain as it gives this error:

`Access to image at 'https://example.workers.dev/96384873_p0.png' from origin 'https://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

How can I allow CORS?

**Comment by jongcs** [comment]
Please check Cloudflare's docs.
https://developers.cloudflare.com/workers/examples/alter-headers
